#!/bin/sh

udevd &
udevadm trigger

fbcp &

# Writable directories. See documentation here:
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export HOME=/tmp/balena
mkdir -p /tmp/balena/xdg_runtime
chmod 0700 /tmp/balena/xdg_runtime
export XDG_RUNTIME_DIR=/tmp/balena/xdg_runtime

# Start Tohora
./tohora 8080 cog &

# wait for it
sleep 1

# ...dary! Post the WPE_URL to Tohora to show that first

wget --post-data "url=http://app:3000" http://localhost:8080 

tail -f /dev/null